apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dp-inntekt-innsyn-ui
spec:
  image: repo.adeo.no:5443/dp-inntekt-innsyn-ui:latest
  port: 8092
  liveness:
    path: /inntekter/health/is-alive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5     # How often (in seconds) to perform the probe. Default to 10 seconds
    failureThreshold: 10 # when a Pod starts and the probe fails,
  readiness:
    path: /inntekter/health/is-alive
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 3
    max: 4
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  vault:
    enabled: true
